### ISSUE TITLE
dev-python/pyperclip-1.5.27 fails to build

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#179] opened 2017-03-28 02:49 UTC
[files.zip](https://github.com/pentoo/pentoo-overlay/files/874359/files.zip)
/usr/bin/python3.4 setup.py install --root=/var/tmp/portage/dev-python/pyperclip-1.5.27/image/_python3.4
/var/tmp/portage/dev-python/pyperclip-1.5.27/temp/environment: line 1044:  9405 Segmentation fault      "${@}"
 * ERROR: dev-python/pyperclip-1.5.27::pentoo failed (install phase):
 *   (no error message)

**Comment by blshkv** [comment] 2017-03-28 03:46
duplicate of https://github.com/pentoo/pentoo-overlay/issues/144

**Closed by blshkv** 2017-03-28 03:46 UTC

**Comment by bill-e-ghote** [comment] 2017-03-28 10:45
My apologies. It is an exact duplicate. Lost track of having submitted it previously, thought I checked for it again before resubmitting it. Failed on both accounts...
