### ISSUE TITLE
new tool: RetDec is a retargetable machine-code decompiler based on LLVM

### ISSUE THREAD

**Issue by gitbugged** [pentoo/pentoo-overlay#258] opened 2017-12-13 19:01 UTC
https://github.com/avast-tl/retdec

**Comment by blshkv** [comment] 2017-12-13 23:43
By reading its build instruction, I suspect the tool is not ready to be part of a distro:
"Warning Do NOT install it into /usr, /usr/local, etc. because our build system is not yet ready for system-wide installations"

**Comment by blshkv** [comment] 2017-12-14 00:10
I can confirm that it does not support system install. There is a huge list of tools need to be forked and build  locally, see https://github.com/avast-tl/retdec/tree/master/deps and it goes on recurcevly. For example, https://github.com/avast-tl/capstone2llvmir/tree/master/deps has it's own recurcive list of deps.

Please open a bug then the tool is ready for production.

**Comment by blshkv** [comment] 2017-12-14 12:44
a649227d18fe4d24824fd5d27bebf3e9cb913729

**Comment by blshkv** [comment] 2018-07-16 01:42
this bug must be fixed in the latest 3.1 version, see https://github.com/avast-tl/retdec/issues/94.
I will be pushing an initial ebuild after basic testing

**Comment by blshkv** [comment] 2018-07-17 14:23
ok, I come up with the first working version. Note: it will fail to install in sandbox env due to internal file downloads

**Comment by blshkv** [comment] 2018-08-18 02:44
d5dd5f7ba14ff22f437ed7505a6023bb3a94ac5a

**Closed by blshkv** 2018-08-18 02:44 UTC
