### ISSUE TITLE
net-analyzer/wpscan-3.6.0: failed to install

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#488] opened 2019-07-25 13:46 UTC
```
>>> Emerging (38 of 38) net-analyzer/wpscan-3.6.0::pentoo
 * wpscan-3.6.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                              [ ok ]
>>> Unpacking source...
 * Running unpack phase for all ...
>>> Unpacking wpscan-3.6.0.tar.gz to /var/tmp/portage/net-analyzer/wpscan-3.6.0/work/all
>>> Source unpacked in /var/tmp/portage/net-analyzer/wpscan-3.6.0/work
>>> Preparing source in /var/tmp/portage/net-analyzer/wpscan-3.6.0/work ...
 * Running prepare phase for all ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby24 ...
 * Running prepare phase for ruby24 ...
 * ACCESS DENIED:  open_wr:      /usr/lib64/ruby/gems/2.4.0/bundler.lock
Resolving dependencies...
Using public_suffix 3.1.1
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib64/ruby/gems/2.4.0
  /usr/lib64/ruby/gems/2.4.0/gems
  /usr/lib64/ruby/gems/2.4.0/specifications
Using addressable 2.6.0
Using bundler 1.17.3
Using nokogiri 1.10.3
Using opt_parse_validator 1.7.3
Using ruby-progressbar 1.10.1
Using ffi 1.11.1
Using ethon 0.12.0
Using typhoeus 1.3.1
Using xmlrpc 0.3.0
Using yajl-ruby 1.4.1
Using cms_scanner 0.5.4
Using wpscan 3.6.0 from source at `.`
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.



Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: ^C

Exiting on signal 2

sandbox:stop  caught signal 2 in pid 4
sandbox:stop  Send signal 4 more times to force SIGKILL
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-4.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/lib64/ruby/gems/2.4.0/bundler.lock
A: /usr/lib64/ruby/gems/2.4.0/bundler.lock
R: /usr/lib64/ruby/gems/2.4.0/bundler.lock
C: /usr/bin/ruby24 -S bundle install --local 
 * --------------------------------------------------------------------------------
```

**Comment by blshkv** [comment] 2019-07-26 02:38
can you try the latest version? I'm unable to reproduce it

**Comment by blshkv** [comment] 2019-07-29 23:09
Fix your system. libsandbox.so is broken or something

**Comment by ZeroChaos-** [comment] 2019-08-23 20:06
it looks like new bundler is trying to write to files it shouldn't be writing to now
"/usr/bin/ruby24 -S bundle install --local" is the command that fails

**Comment by joecool1029** [comment] 2019-10-18 22:57
Sorry for the long followup to this. This issue is caused by broken rubygems that's included in the portage tree: https://bugs.gentoo.org/688310 

Workaround is to mask >=dev-ruby/rubygems-3.0.4

**Comment by blshkv** [comment] 2019-10-19 00:59
It's good to know, thanks. But the latest stable rubygems is 2.7.9. Use stable Gentoo with our keywords or face and deal with Gentoo bug on your own ;-) Sorry. We can't simply mask >=3.0.4 because it might get fixed in 3.0.7

**Closed by blshkv** 2019-10-19 00:59 UTC

**Comment by blshkv** [comment] 2020-03-22 00:17
Michel (https://bugs.gentoo.org/688310#c10) suggested that `bundle check` may be enough, something to double check

**Comment by joecool1029** [comment] 2020-10-29 08:28
> Michel (https://bugs.gentoo.org/688310#c10) suggested that `bundle check` may be enough, something to double check

Seems to work, submitted a PR since it's been over a year now and wanted to be able to purge old ruby stuff on my system: https://github.com/pentoo/pentoo-overlay/pull/685

**Comment by ZeroChaos-** [comment] 2020-10-29 12:43
We are running ruby26 and do not have this issue.  I suspect the problem is a grossly out of date system.
