### ISSUE TITLE
[GNURadio] is broken in pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo-overlay#289] opened 2018-07-07 17:26 UTC
hi,
 i tried to use GNURadio of the **pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso**
but every time i try to start a gnuradio flowgraph i get an error message and nothing else happens.
![screenshot_2018-07-07_17-05-41](https://user-images.githubusercontent.com/4750719/42413137-57cf1aec-821a-11e8-907a-83d4f9eaf986.png)

it doesn't matter how simple or complicated the gnuradio flowgraph is, i always get that error.
even a **NULL Source** connected to a **NULL Sink** gives that error.

```
pentoo@pentoo ~ $ uname -a
Linux pentoo 4.17.2-pentoo #1 SMP Wed Jul 4 00:53:46 UTC 2018 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux


pentoo@pentoo ~ $ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.7.13.3 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks

Loading: "/home/pentoo/test-noise.grc"
>>> Done

Generating: '/home/pentoo/top_block.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python2.7 -u /home/pentoo/top_block.py

Traceback (most recent call last):
  File "/home/pentoo/top_block.py", line 143, in <module>
    main()
  File "/home/pentoo/top_block.py", line 131, in main
    tb = top_block_cls()
  File "/home/pentoo/top_block.py", line 58, in __init__
    self.restoreGeometry(self.settings.value("geometry"))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType'

>>> Done

```

[test-noise.zip](https://github.com/pentoo/pentoo-overlay/files/2172942/test-noise.zip)

i just booted into Pentoo latest beta (**pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso**) via PXE-Boot,
started GNURadio, created/loaded a flowgraph and tried to start it.

when i do that same thing under **pentoo-amd64-hardened-2018.0_RC6.3.iso** everything works just fine.

**Comment by blshkv** [comment] 2018-07-08 07:29
you should have filed a report at https://github.com/pentoo/pentoo-livecd/issues.

Anyway, loaded that iso, gnuradio is broken indeed. The broken version is 3.7.11-r3. The next version ```3.7.13.3``` seems ok. So just upgrade with: ```emerge --sync && emerge -1u net-wireless/gnuradio```. The next ISO will include this version automatically.

**Comment by beta-tester** [comment] 2018-07-08 08:07
thank you for the temporary solution.

> you should have filed a report at https://github.com/pentoo/pentoo-livecd/issues.

sorry, lost the overview what project is responsable for which part.
shall i open an issue report there?

**Comment by blshkv** [comment] 2018-07-08 09:11
no need, thanks. Just need to a next iso cut

**Comment by beta-tester** [comment] 2018-07-08 14:57
i think it is a GNURadio issue and not a Pentoo issu.
i now used the normal Pentoo version with the working GNURadio version and made an update to GNURadio 3.7.13.3.
after theupdate GNURadio showed the issue on that Pentoo version as well.

will see, if i can find how to install that version on an other linux distro to be sure if it is an GNURadio issue.

**Comment by blshkv** [comment] 2018-07-08 16:06
I can't reproduce on my laptop. Your sample runs smoothly. 
Can you change your profile to non-binary (eselect profile set pentoo:pentoo/default/linux/amd64) and *recompile* gnuradio?

**Comment by beta-tester** [comment] 2018-07-08 21:02
you mean i should do the following steps?
```
sudo eselect profile set pentoo:pentoo/default/linux/amd64
sudo emerge --sync
sudo emerge net-wireless/gnuradio
```
no, makes no difference on the pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso.

sorry, i am more a debian like'ish distribution user - using apt-get to install software...
i am an absolutely noob in Gentoo'ish distributions.
my knowledge of Gentoo is very close to ZERO (or sub-zero).
i hope i slowly begin to start to understand the philosophy of Gentoo and what it means to "install" software there... 

i only use Pentoo from an ISO and boot into it. there is no permanent persistent installation.
Pentoo is used because it offers the most recent version of all applications out of the box i like use from time to time - in my case it is GNURadio.

if you were using the ISO images i told and you couldn't see those issues, then it must be related to the kind of how to start Pentoo (ISO booted via phisical DVD or via PXE-boot) or it is related to the used hardware.

tomorrow i will see if it makes a different when using a physical DVD instead of PXE-boot.

**Comment by ZeroChaos-** [comment] 2018-07-09 13:11
```

>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

```

He is probably crashing from ignoring this warning.  Either way,
gnuradio issues should he reported upstream.

**Comment by blshkv** [comment] 2018-07-09 14:03
I have the same warning. But he mentioned that the issue appears only then the iso booted via PXE.
Let's see if @beta-tester can provide more details.

**Comment by beta-tester** [comment] 2018-07-09 18:53
i just burned the two Pentoo Live ISOs (most recent Pentoo and Pentoo Beta) to a physical DVD and tested them on two different computers each.
absolute the same behavior.

> I have the same warning. But he mentioned that the issue appears only then the iso booted via PXE.
> Let's see if @beta-tester can provide more details.

misunderstood...
i tried to mentioned that i normally just use PXE-boot and never tested Pentoo from a physical media before.
now i tested with a physical media as well.

the Warning is shown on the working GNURadio ( 3.7.11-r3) installation as well.
so this can not be the cause of the broken GNURadio 3.17.13.3.

currently i am not able to compile GNURadio 3.17.13.3 on a different Linux Live distribution.

**Comment by blshkv** [comment] 2018-07-10 02:41
@beta-tester not sure about a DVD (these are gone together with floppies and tapes), but we test it with USB drivers usually. Can you run ```dd if=./pentoo.iso of=./dev/sdX bs=1024k``` where X is your USB and test it again?

***Please re-download*** your ISO as it has changed without version modification. @ZeroChaos- why?

**Comment by beta-tester** [comment] 2018-07-10 10:09
i just created an USB-Stick of **pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso** and booted into it.
there GNURadio shows up the same issue (exception and not running the flow graph):

```
...

Executing: /usr/bin/python2.7 -u /home/pentoo/top_block.py

Traceback (most recent call last):
  File "/home/pentoo/top_block.py", line 143, in <module>
    main()
  File "/home/pentoo/top_block.py", line 131, in main
    tb = top_block_cls()
  File "/home/pentoo/top_block.py", line 58, in __init__
    self.restoreGeometry(self.settings.value("geometry"))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType'
```
absolute no different to USB, DVD, PXE -boot. i don't know, why it is only me how see that exception.

i could find a debian like linux distribution where GNURadio 3.17.33.3 can be installed.
there i don't get that exception and the gnuradio flow graph is executing smoothly.
(i get the audio warning there as well, but that warning does not break anything).

the used distribution is [Parrto 4.1](https://cdimage.parrotsec.org/parrot/iso/4.1/Parrot-security-4.1_amd64.iso).
to update to gnuradio 3.17.33.3 i did the following steps:
```
sudo apt update
sudo apt install --only-upgrade -y gnuradio
```

i compared the top_block.py files that was complained by gnuradio in Pentoo Beta
and the line that throwed the exception looks different.

diff "[top_block_py-pentoo_gr3_17_33_3.txt](https://github.com/pentoo/pentoo-overlay/files/2179842/top_block_py-pentoo_gr3_17_33_3.txt)"  "[top_block_py-parrot_gr3_17_33_3.txt](https://github.com/pentoo/pentoo-overlay/files/2179843/top_block_py-parrot_gr3_17_33_3.txt)"
```
-        self.restoreGeometry(self.settings.value("geometry"))
+        self.restoreGeometry(self.settings.value("geometry", type=QtCore.QByteArray))
```

i can not tell you, what commit of gnuradio 3.17.33.3 is installed exactly on Pentoo Beta and Parrot 4.1...

if you don't have further ideas or instructions i can do, then you can close the issue and i'll give up.

**Comment by blshkv** [comment] 2018-07-10 11:17
interesting. I think you narrowed it. We are very close to find a root case

**Comment by beta-tester** [comment] 2018-07-11 05:42
i made some further tests...
the top_block.py is generated from a template located in Pentoo here:
```
/usr/lib64/python2.7/site-packages/gnuradio/grc/core/generator/flow_graph.tmpl
/mnt/overlay/.upper/usr/lib64/python2.7/site-packages/gnuradio/grc/core/generator/flow_graph.tmpl
(/mnt/livecd/usr/lib64/python2.7/site-packages/gnuradio/grc/core/generator/flow_graph.tmpl)
```
i tried to changed 
`self.restoreGeometry(self.settings.value("geometry"))`
to
`self.restoreGeometry(self.settings.value("geometry", type=QtCore.QByteArray))`
to see what happens...

after the change gnuradio doesn't throw that exception anymore ater the change. on the console every think looks good...
**BUT** the normal window, with the controles/instruments on it, doesn't pop up as it would usually.
so i guess there must be more wrong with that gnuradio installation.

i searched for commits on the gnuradio project, if there were a change in that flow_graph.tmpl recently, but i couldn't find one that is related to that code line `self.restoreGeometry(self.settings.value("geometry"))`.
no idea, where that line/file is comming from in the Pentoo installation.

and i am much more wondering, why you can't reproduce what i observed.
don't we use the same iso images? are there different version of
https://www.pentoo.ch/isos/Beta/Pentoo_amd64_hardened/pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso ?

i hope it is only a temporary issue during the pre-release beta phase...
thank you for your work... have a nice time.

**Comment by blshkv** [comment] 2018-07-11 06:31
nice catch. Gentoo provided their own patches gnuradio-3.7.12-qt5.tar.xz
@ZeroChaos-  it is hosted under your directory (https://dev.gentoo.org/~zerochaos/patches), please investigate!

**Comment by beta-tester** [comment] 2018-07-11 06:37
BTW: the new iso 
https://www.pentoo.ch/isos/Pentoo_amd64_hardened/pentoo-amd64-hardened-2018.0_RC7.1.iso
shows the same issue.

**Comment by blshkv** [comment] 2018-07-11 06:48
That is correct, the same patches are applied to the latest gnuradio, you can check the ebuild. I suspect ZC has to backport and apply them because QT4 has been removed from gentoo

**Comment by ZeroChaos-** [comment] 2018-07-11 20:46
this should be fixed in gnuradio-3.7.13.3-r1, which will be in RC7.2 in a day or so

**Closed by ZeroChaos-** 2018-07-11 20:46 UTC

**Comment by blshkv** [comment] 2018-07-12 01:39
The changes looks massive. Thank you both!

**Comment by beta-tester** [comment] 2018-07-18 08:31
gnuradio is working on **RC7.2**...
thank you very much.

BTW: is there a more clean and straightforward way to install **gr-iio**?
currently i do:
```
sudo emerge --sync

# to add gnuradio "overlay"
sudo layman -a gnuradio

# to unmask masked packages
sudo emerge --autounmask --autounmask-write gr-iio
sudo dispatch-conf
# 2x [u] = use-new

# to finally install gr-iio
sudo emerge gr-iio
```

**Comment by blshkv** [comment] 2018-07-18 11:09
That --autounmask option is "lazy" and unmask to widely often.
I suggest to run this command with -pv option, copy-paste the list to your accept_keywords manually.
After that, you can drop dispatch-conf.

Other than that, it's all good. Let's hope the gnuradio overlay guys developed a working ebuild ;-)

**Comment by beta-tester** [comment] 2018-08-06 10:06
gnuradio is broken again on 
https://www.pentoo.ch/isos/latest-iso-symlinks/Beta/pentoo-beta-amd64-hardened-latest.iso
(2018-07-31 13:56  2.1G)

now it throws the following error message:
```
pentoo@pentoo ~ $ gnuradio-companion --version
Traceback (most recent call last):
  File "/usr/bin/gnuradio-companion", line 99, in <module>
    run_main()
  File "/usr/bin/gnuradio-companion", line 87, in run_main
    from gnuradio.grc.main import main
  File "/usr/lib64/python2.7/site-packages/gnuradio/grc/main.py", line 23, in <module>
    from .gui.Platform import Platform
  File "/usr/lib64/python2.7/site-packages/gnuradio/grc/gui/Platform.py", line 23, in <module>
    from ..core.Platform import Platform as _Platform
  File "/usr/lib64/python2.7/site-packages/gnuradio/grc/core/Platform.py", line 27, in <module>
    from .generator import Generator
  File "/usr/lib64/python2.7/site-packages/gnuradio/grc/core/generator/__init__.py", line 18, in <module>
    from Generator import Generator
  File "/usr/lib64/python2.7/site-packages/gnuradio/grc/core/generator/Generator.py", line 23, in <module>
    from Cheetah.Template import Template
ImportError: No module named Cheetah.Template
```

please tell me, if i shall stop reporting issues on beta/prerepease versions of pentoo.

**Comment by beta-tester** [comment] 2018-08-06 10:54
just realized, that https://www.pentoo.ch/isos/latest-iso-symlinks/Beta/pentoo-beta-amd64-hardened-latest.iso is **NOT** pointing to the **FULL** version of pentoo.

gnuradio **IS** woring on the beta version of pentoo "**FULL**"
https://www.pentoo.ch/isos/Beta/Pentoo_amd64_hardened/pentoo-full-amd64-hardened-2018.0_RC7.2_p20180730.iso

only the _lighter_ pentoo version is affected of broken gnuradio
https://www.pentoo.ch/isos/Beta/Pentoo_amd64_hardened/pentoo-amd64-hardened-2018.0_RC7.2_p20180730.iso

so possibly an issue for case https://github.com/pentoo/pentoo.github.io/issues/4

**Comment by ZeroChaos-** [comment] 2018-08-06 11:15
Cheetah obviously should be in RDEPEND, I will get that fixed, thanks!

**Comment by blshkv** [comment] 2018-08-06 11:19
@beta-tester Please continue bugging us. We need your hard work to release a working iso.
