### ISSUE TITLE
dev-util/ghidra-9.1.1 fails to emerge

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#547] opened 2020-01-31 19:36 UTC
Based on prior issues reported here, I used this command line:

COLORTERM=truecolor TERM=xterm-color emerge dev-util/ghidra

The COLORTERM and TERM settings did not help. The same error was seen without those.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Generic:compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

I tried with every java-vm I currently have installed. Of course, icedtea-bin-8 was doomed as 11 is required, but I tried anyway.

$ eselect java-vm list
Available Java Virtual Machines:
  [1]   default-java 
  [2]   icedtea-bin-8 
  [3]   openjdk-11  system-vm
  [4]   openjdk-bin-11 

[ghidra-emerge-out.txt](https://github.com/pentoo/pentoo-overlay/files/4141074/ghidra-emerge-out.txt)

**Comment by blshkv** [comment] 2020-01-31 21:15
Try uninstalling all java but one. Keep jdk-11. It is still masked in Gentoo due to this bug

**Comment by bill-e-ghote** [comment] 2020-01-31 21:20
I will try that.
Unfortunately, dev-java/swt will not emerge at all with openjdk-11, but does emerge OK with icedtea-bin-8. I suppose I could always add openjdk-8 back again at a later time (if needed) and drop icedtea altogether.

**Comment by blshkv** [comment] 2020-02-01 01:03
I can confirm the swt bug, it is also reported in the b.g.o:
https://bugs.gentoo.org/689976

That basically means that you have to emerge -1 swt with jdk-8 first, switch ```eselect java system``` to jdk-11 and try to install ghidra. Having just two icedtea-bin-8 and openjdk-11 was working for me. But you might need to uninstall jdk-8 and the end.

These are all Gentoo bugs, forking system java files is not an option. Closing this bug report for now.

**Closed by blshkv** 2020-02-01 01:03 UTC
