### ISSUE TITLE
dev-util/semgrep-core-bin: source directory does not exist

### ISSUE THREAD

**Issue by LemonBreezes** [pentoo/pentoo-overlay#1871] opened 2024-04-06 17:52 UTC
```text
 * Package:    dev-util/semgrep-core-bin-1.66.0:0
 * Repository: pentoo
 * Maintainer: unknown@pentoo.ch
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux
 * FEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
>>> Unpacking semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl to /var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/work
unpack semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl: file format not recognized. Ignoring.
>>> Source unpacked in /var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/work
 * ERROR: dev-util/semgrep-core-bin-1.66.0::pentoo failed (prepare phase):
 *   The source directory '/var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/work/semgrep-1.66.0.data' doesn't exist
 * 
 * Call stack:
 *            ebuild.sh, line  784:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1072:  Called __dyn_prepare
 *   phase-functions.sh, line  400:  Called die
 * The specific snippet of code:
 *   		die "The source directory '${S}' doesn't exist"
 * 
 * If you need support, post the output of `emerge --info '=dev-util/semgrep-core-bin-1.66.0::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/semgrep-core-bin-1.66.0::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/empty'
 * S: '/var/tmp/portage/dev-util/semgrep-core-bin-1.66.0/work/semgrep-1.66.0.data'
```

**Comment by blshkv** [comment] 2024-06-06 08:17
can't confirm it

```
ebuild semgrep-core-bin-1.66.0.ebuild fetch 
>>> Downloading 'http://distfiles.gentoo.org/distfiles/8d/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl'
--2024-06-06 16:16:21--  http://distfiles.gentoo.org/distfiles/8d/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl
Resolving distfiles.gentoo.org... 79.127.235.3, 79.127.235.6, 79.127.235.12, ...
Connecting to distfiles.gentoo.org|79.127.235.3|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-06-06 16:16:23 ERROR 404: Not Found.

>>> Downloading 'https://files.pythonhosted.org/packages/cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311/s/semgrep/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl'
--2024-06-06 16:16:23--  https://files.pythonhosted.org/packages/cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311/s/semgrep/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl
Resolving files.pythonhosted.org... 199.232.44.223, 2a04:4e42:48::223
Connecting to files.pythonhosted.org|199.232.44.223|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.pythonhosted.org/packages/58/da/d1d4681d8e73b7b27223822281c915b672914b0713248378aa7045e110d5/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl [following]
--2024-06-06 16:16:23--  https://files.pythonhosted.org/packages/58/da/d1d4681d8e73b7b27223822281c915b672914b0713248378aa7045e110d5/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl
Reusing existing connection to files.pythonhosted.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 26981792 (26M) [application/octet-stream]
Saving to: ‘/var/cache/distfiles/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl.__download__’

/var/cache/distfiles/semgrep-1.66.0-c 100%[======================================================================>]  25.73M  2.08MB/s    in 12s     

2024-06-06 16:16:36 (2.12 MB/s) - ‘/var/cache/distfiles/semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl.__download__’ saved [26981792/26981792]

 * semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl BLAKE2B SHA512 size ;-) ...
 ```

**Comment by WGH-** [comment] 2024-06-11 15:03
I'm having the same problem. The problem is `unpack`  can't handle `.whl` files, because it determines the unpacker solely by extension: https://github.com/gentoo/portage/blob/portage-3.0.63/bin/phase-helpers.sh#L319-L575

> can't confirm it
> 
> `ebuild semgrep-core-bin-1.66.0.ebuild fetch`

Well, yes, now try at least `ebuild semgrep-core-bin-1.66.0.ebuild prepare` :)

**Comment by blshkv** [comment] 2024-06-11 15:24
oops, my bad. Should be fixed. Thanks for reporting!

**Closed by blshkv** 2024-06-11 15:24 UTC
