### ISSUE TITLE
dev-libs/radare2-bindings-1.6.0:0::pentoo cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’

### ISSUE THREAD

**Issue by l29ah** [pentoo/pentoo-overlay#222] opened 2017-07-26 02:11 UTC
```
>>> Starting src_compile
make -j5
make -C libr/lang/p

(pkg-config:10140): GLib-CRITICAL **: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

(pkg-config:10149): GLib-CRITICAL **: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
make[1]: Entering directory `/var/tmp/paludis/dev-libs-radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc python.c -O2 -pipe -O2 -pipe -march=native -I/usr/include/libr -I/usr/include/python2.7 -I/usr/include/python2.7  -OPT:Olimit=0 -O2 -pipe -O2 -pipe -march=native -fwrapv -DNDEBUG -DPYVER=2 -lpython2.7 -lpthread -ldl -lutil -lm -L/usr/lib  -lr_core -lr_io -lr_util -shared \
-Wl,-O1 -Wl,--as-needed  -lr_core -lr_io -lr_util -shared -fPIC -o lang_python2.so
cc -fPIC  -lr_core -lr_io -lr_util -shared -o lang_csharp.so \
	-I/usr/include/libr -lr_util csharp.c
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
make[1]: *** [lang_python.so] Error 1
```

**Comment by blshkv** [comment] 2017-07-26 02:37
do you have an invalid settings in the make.conf file? 
```-OPT:Olimit=0 ```

**Comment by blshkv** [comment] 2017-07-26 02:45
I'm closing the issue since it seems like the problem is in your settings. Please re-open if I'm wrong.
Thank you.

**Comment by l29ah** [comment] 2017-07-26 08:48
On Tue, Jul 25, 2017 at 07:37:20PM -0700, Anton Bolshakov wrote:
> do you have an invalid settings in the make.conf file? 
> ```-OPT:Olimit=0 ```

No. Every other package builds fine.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment] 2017-07-26 08:49
I can't reopen it since i'm not a project collaborator.

**Comment by blshkv** [comment] 2017-07-26 11:25
Please post a full build.log and emerge - - info output

**Comment by l29ah** [comment] 2017-07-26 13:35
```
n   dev-libs/radare2-bindings:0::pentoo 1.6.0 to ::installed
    "Language bindings for radare2"
    -ctypes cxx -guile -lua -perl -php5 python -ruby PYTHON_TARGETS: python2_7 build_options: symbols=compress -dwarf_compress -optional_tests -trace work=tidyup
```
```
Output from installing dev-libs/radare2-bindings-1.6.0:0::pentoo to ::installed:

Checking 'radare2-bindings-1.6.0.tar.gz'... ok
>>> Running ebuild phase killold as root:root...
>>> Starting builtin_killold
>>> Done builtin_killold
>>> Completed ebuild phase killold
>>> Running ebuild phases init saveenv as portage:portage...
>>> Starting builtin_init
>>> Done builtin_init
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases init saveenv
>>> Running ebuild phases loadenv setup saveenv as root:root...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting pkg_setup
>>> Done pkg_setup
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv setup saveenv
>>> Running ebuild phases loadenv unpack saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_unpack
>>> Unpacking radare2-bindings-1.6.0.tar.gz to /var/tmp/paludis/dev-libs-radare2-bindings-1.6.0/work
tar zxf /var/paludis/distfiles/radare2-bindings-1.6.0.tar.gz --no-same-owner
>>> Done src_unpack
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv unpack saveenv
>>> Running ebuild phases loadenv prepare saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_prepare
 * Applying 01_use_python_2.7.patch ...                                                                                                                                                                                     [ ok ]
>>> Done src_prepare
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv prepare saveenv
>>> Running ebuild phases loadenv configure saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_configure
./configure --prefix=/usr --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/radare2-bindings-1.6.0 --libdir=/usr/lib64 --enable=cxx,python --build=x86_64-pc-linux-gnu
==> Using valabind 0.10.0
==> Using swig 3.0.12
Checking valabind languages support...
 - python: no
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: no
 - java: yes
 - guile: no
 - php5: no
 - node-ffi: no
 - ctypes: yes
 - ocaml: no
 - cxx: yes (g++)
 - valac: no
Supported langs:
 - cxx
 - python
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
using crosscompilation mode.
checking for working directories... current
using prefix '/usr'
checking for c compiler... x86_64-pc-linux-gnu-gcc
checking for c++ compiler... x86_64-pc-linux-gnu-g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... /usr/bin/g-ir-compiler
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_SWIG = 1
 - HAVE_VALABIND = 1
 - HAVE_GIRCOMPILER = 1
>>> Done src_configure
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv configure saveenv
>>> Running ebuild phases loadenv compile saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_compile
make -j5
make -C libr/lang/p

(pkg-config:10140): GLib-CRITICAL **: g_string_insert_len: assertion 'len == 0 || val != NULL' failed

(pkg-config:10149): GLib-CRITICAL **: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
make[1]: Entering directory `/var/tmp/paludis/dev-libs-radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc python.c -O2 -pipe -O2 -pipe -march=native -I/usr/include/libr -I/usr/include/python2.7 -I/usr/include/python2.7  -OPT:Olimit=0 -O2 -pipe -O2 -pipe -march=native -fwrapv -DNDEBUG -DPYVER=2 -lpython2.7 -lpthread -ldl -lutil -lm -L/usr/lib  -lr_core -lr_io -lr_util -shared \
-Wl,-O1 -Wl,--as-needed  -lr_core -lr_io -lr_util -shared -fPIC -o lang_python2.so
cc -fPIC  -lr_core -lr_io -lr_util -shared -o lang_csharp.so \
	-I/usr/include/libr -lr_util csharp.c
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
make[1]: *** [lang_python.so] Error 1
make[1]: *** Waiting for unfinished jobs....

Error:
  * In program /usr/bin/cave --colour yes perform install --hooks --managed-output --output-exclusivity with-others =dev-libs/radare2-bindings-1.6.0:0::pentoo --destination installed --x-of-y 2 of 3, 1 failed:
  * When installing 'dev-libs/radare2-bindings-1.6.0:0::pentoo':
  * When running an ebuild command on 'dev-libs/radare2-bindings-1.6.0:0::pentoo':
  * Install failed for 'dev-libs/radare2-bindings-1.6.0:0::pentoo' (paludis::ActionFailedError)

make[1]: Leaving directory `/var/tmp/paludis/dev-libs-radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
make: *** [all] Error 2

!!! ERROR in dev-libs/radare2-bindings-1.6.0::pentoo:
!!! In /usr/libexec/paludis/utils/emake at line 30
!!! emake returned error 2

!!! Call stack:
!!!    * paludis_die_or_error_func (/usr/libexec/paludis/die_functions.bash:82)
!!!    * main (/usr/libexec/paludis/utils/emake:30)

diefunc: making ebuild PID 9991 exit with error
die trap: exiting with error.

Failed install to / for dev-libs/radare2-bindings-1.6.0:0::pentoo
```

Not sure what would be `emerge --info` with paludis.

**Comment by blshkv** [comment] 2017-07-26 13:55
Please find out where that "OTP" parameter is coming from.

I'm unable to reproduce, here is what I have:
```
make[1]: Entering directory '/var/tmp/portage/dev-libs/radare2-bindings-1.6.0/work/radare2-bindings-1.6.0/libr/lang/p'
cc python.c -march=native -O2 -pipe -I/usr/include/libr  -I/usr/include/texlua52  -I/usr/include/python2.7 -I/usr/include/python2.7  -march=native -O2 -pipe -fwrapv -DNDEBUG -DPYVER=2 -lpython2.7 -lpthread -ldl -lutil -lm -L/usr/lib  -lr_core -lr_io -lr_util -shared \
-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu  -lr_core -lr_io -lr_util -shared -fPIC -o lang_python2.so
cc -fPIC  -lr_core -lr_io -lr_util -shared -o lang_csharp.so \
        -I/usr/include/libr -lr_util  csharp.c
```

**Comment by blshkv** [comment] 2017-07-26 14:01
Does this help? https://forums.gentoo.org/viewtopic-p-7505182.html
I bet it has something to do with python, can you post ```python-config --cflags``` output?

**Comment by blshkv** [comment] 2017-07-27 02:33
ok, so I think it clear that this issue has nothing to do with pentoo or radare2-bindings. Please find and fix the root cause of invalid compilation option.
This bug might be related:
https://bugs.gentoo.org/show_bug.cgi?id=596798

**Closed by blshkv** 2017-07-27 02:33 UTC

**Comment by l29ah** [comment] 2017-07-27 12:21
I think not as there's nothing to fix apparently, as `python-config --cflags` doesn't output such flags:
```
‰ python-config --cflags
-I/usr/include/python3.4m -I/usr/include/python3.4m  -Wno-unused-result -O2 -pipe -O2 -pipe -march=native -fwrapv -DNDEBUG 
```

**Comment by l29ah** [comment] 2017-07-27 12:21
Oh, although python2-config does, okay.
