### ISSUE TITLE
config :: privoxy

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#664] opened 2020-08-05 22:20 UTC
The default privoxy config /etc/privoxy/config lack dot on the end of: forward-socks4a / 127.0.0.1:9050
Moreover to start this service user have to create /var/log/privoxy with privoxy:privoxy permissions - can we create this folder for livecd?

**Comment by ZeroChaos-** [comment] 2020-08-05 22:22
this is a gentoo package, if folders and perms are not set right then it's a gentoo bug.  I'll adjust the config because that is my fault

**Comment by blshkv** [comment] 2020-08-24 23:59
it is a gentoo package. Please open a new bug at https://bugs.gentoo.org/. I'm trying to keep a minimum amount of open issues here

**Comment by ZeroChaos-** [comment] 2020-08-25 00:00
I still need this tracker  I haven't fixed the config yet.

**Comment by blshkv** [comment] 2020-08-25 00:02
you are not listed as a maintainer, but ok. Please do it sooner. Should take 15 min but the bug is open for 20 days with no action

**Comment by ZeroChaos-** [comment] 2020-08-25 00:04
Believe it or not, wagging your keyboard won't fix the bug.  If you spent half the time you spend complaining doing actual testing and bug fixing we would have a stable distro.  Quit starting arguments on GitHub and do something useful.

**Comment by blshkv** [comment] 2020-08-25 00:13
well, guess what? I still can write ;-)
I was about to fork and fix it, but discovered privoxy-3.0.28-r2.ebuild is in the portage, both issues are fixed.

@ostree Please test  and report all issues where it belongs

**Comment by ZeroChaos-** [comment] 2020-08-25 00:22
The issue is in our script that runs during livecd creation  so I strongly doubt it.  No matter what that has to be fixed.

**Comment by blshkv** [comment] 2020-08-25 00:27
so I opened a livecd  bug https://github.com/pentoo/pentoo-livecd/issues/39 and you said it's a gentoo bug? Can you make up your mind?

**Comment by ZeroChaos-** [comment] 2020-08-25 00:28
The config file bug is mine, the log file bug is gentoo's, I have not flip flopped.

**Comment by blshkv** [comment] 2020-08-25 00:31
so the config is fixed, the log file is getting created as I reported. Can close now?

**Comment by blshkv** [comment] 2020-08-25 00:32
github dosn't pick up automatically anymore. This  is the config fix:  https://github.com/pentoo/pentoo-livecd/commit/793504e5c73871b700d22af9e45df5d9ca4177cb

**Comment by ZeroChaos-** [comment] 2020-08-25 00:34
Yup, thanks for sending 1000 characters of whining about a single character fix you did yourself

**Closed by ZeroChaos-** 2020-08-25 00:34 UTC

**Comment by blshkv** [comment] 2020-08-25 00:36
it is a livie-cd bug which you keep breaking. I don't want to touch it. It took 5 seconds to fix it. The report doesn't need to sit for 20 days in  wrong place
