### ISSUE TITLE
Pentoo  RC4.6 Installer Not Working

### ISSUE THREAD

**Issue by DaKahuna** [pentoo/pentoo-overlay#63] opened 2016-01-09 20:02 UTC
After going through all of the steps to install Pentoo in a VMware Workstation virtual machine (60GB Hard drive, 4 GB RAM, 1 processor core) all of the steps complete and when I go to exit the main install window I get an error message saying an error was encountered. I go back to the main install window and select exit again and it exits back to the screen from which I ran the install tool (same issue occurs in both the GUI and from the command line). When I rebooth the VM, grub fails to run and all I get is a black screen.

Attached is the /tmp/pentoo-installer.log for reference as requested on IRC by Zero_Chaos. (renamed to pentoo-installer.txt since .log is unsupported for attachments).

[pentoo-installer-VMware.txt](https://github.com/pentoo/pentoo-overlay/files/83816/pentoo-installer-VMware.txt)

At blshkv's request I tried installing Pentoo RC4.6 on my Windows 10 Host using VirtualBox instead of VMware. Attached is the pentoo-installer.txt file from that effort. It also failed the same as under VMware.

[pentoo-installer-Virtual-Box.txt](https://github.com/pentoo/pentoo-overlay/files/83817/pentoo-installer-Virtual-Box.txt)

**Comment by DaKahuna** [comment] 2016-01-13 02:23
Went through the same install procedure under VMware Fusion and exact same thing happened.  In all cases I have downloaded a new .iso file for the amd64 dated November 28, 2015.

**Comment by blshkv** [comment] 2016-01-13 04:00
I managed to reproduce the error.

The installer creates 3 partitions by default:
sda1 (boot)
sda2 (root)
sda3 (swap)

Currently, the grub files are getting installed into sda2 /mnt/gentoo/boot and no files on
sda3 at all.

Also, sda3 partition type is wrong. It must be marked as 82 (swap) but it is marked as 83 (Linux).

**Comment by blshkv** [comment] 2016-01-13 04:29
oh, that's basically the duplicate of https://github.com/pentoo/pentoo-installer/issues/8

**Closed** 2016-01-13 04:30 UTC
