### ISSUE TITLE
ERROR: net-analyzer/wpscan-3.8.6::pentoo failed (prepare phase): on Gentoo ~amd64

### ISSUE THREAD

**Issue by xp-vit** [pentoo/pentoo-overlay#676] opened 2020-09-13 10:37 UTC
net-analyzer/wpscan-3.8.6::pentoo  failes to install with following error:

````
Using wpscan 3.8.6 from source at `.`
 * ACCESS DENIED:  mkdir:        /usr/lib64/ruby/gems/2.5.0/bin
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib64/ruby/gems/2.5.0/bin
An error occurred while installing wpscan (3.8.6), and Bundler cannot continue.


In Gemfile:
  wpscan
 * ERROR: net-analyzer/wpscan-3.8.6::pentoo failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_prepare
 *   environment, line 2114:  Called ruby-ng_src_prepare
 *   environment, line 1773:  Called _ruby_each_implementation 'each_ruby_prepare'
 *   environment, line  546:  Called _ruby_invoke_environment 'ruby25' 'each_ruby_prepare'
 *   environment, line  667:  Called each_ruby_prepare
 *   environment, line  851:  Called die
 * The specific snippet of code:
 *       MSF_ROOT="." BUNDLE_GEMFILE=Gemfile ${RUBY} -S bundle install --local || die;
 * 
 * If you need support, post the output of `emerge --info '=net-analyzer/wpscan-3.8.6::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=net-analyzer/wpscan-3.8.6::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/net-analyzer/wpscan-3.8.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-analyzer/wpscan-3.8.6/temp/environment'.
 * Working directory: '/var/tmp/portage/net-analyzer/wpscan-3.8.6/work/ruby25/wpscan-3.8.6'
 * S: '/var/tmp/portage/net-analyzer/wpscan-3.8.6/work/ruby25/wpscan-3.8.6'
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/tmp/portage/net-analyzer/wpscan-3.8.6/temp/sandbox.log"
 * 
````

This seems to be sandbox rules violation. --info and build.log files are attached.

 * LOG FILE: "/var/tmp/portage/net-analyzer/wpscan-3.8.6/temp/sandbox.log" - not present.

[wpscan-3.8.6-info.txt](https://github.com/pentoo/pentoo-overlay/files/5213932/wpscan-3.8.6-info.txt)
[wpscan-3.8.6-build.txt](https://github.com/pentoo/pentoo-overlay/files/5213933/wpscan-3.8.6-build.txt)

Also wpscan can be updated to 3.8.7: https://github.com/wpscanteam/wpscan/releases/tag/v3.8.7

Thanks a lot for the AWESOME overlay!

**Comment by blshkv** [comment] 2020-09-13 11:20
uff... there is MSF_ROOT env left over which has changed recently.

**Comment by blshkv** [comment] 2020-09-13 12:02
form what I see, you are using the latest and the greatest ruby packages including bundler:2

Use our profile or you are on your own ;-)

**Comment by xp-vit** [comment] 2020-09-13 12:21
@blshkv I'm using Gentoo ~amd64 and just added `pentoo` overlay using `layman -a pentoo` as it's described in README.md file of this repo(https://github.com/pentoo/pentoo-overlay/blob/master/README.md). I'm using ruby25 profile:

````
eselect ruby list
Available Ruby profiles:
  [1]   ruby25 (with Rubygems) *
  [2]   ruby27
````

Would you be so kind to point to any documentation describing what else should I do?

**Comment by xp-vit** [comment] 2020-09-13 13:18
Oh, I see that pentoo adds own profiles to `eselect profile list`. Probably it's a bit to extreme to switch gentoo installation to different profile. But thanks for your answers anyway!

**Comment by blshkv** [comment] 2020-09-14 00:38
we discussed it on IRC, here is a reference if someone hit similar bug:
https://github.com/pentoo/pentoo-overlay/wiki/Set-up

**Comment by xp-vit** [comment] 2020-09-14 14:39
Actually using pentoo profile not really solving the issue on Gentoo ~amd64. I have:
1. Added pentoo overlay on my Gentoo using layman: `layman -a pentoo`
2. `eselect profile set pentoo:default/linux/amd64/17.1/desktop`

wpscan failes with the same error... There might be something else. I have rather fresh Gentoo installation (from April). So, I don't think that this bug can be really closed.

**Comment by ZeroChaos-** [comment] 2020-09-14 14:42
The point of that bundler line is that it throws sandbox errors if we get the deps wrong.  I strongly suspect the deps are wrong or missing something.  That, or bundler 2.x has changed how bundle install --local works

**Comment by blshkv** [comment] 2020-09-14 14:48
If you added ~amd64 into make.conf you overwrote pentoo profile

**Comment by ZeroChaos-** [comment] 2020-09-14 14:50
After 10 seconds of looking at the ebuild the problem is *obviously* because the deps weren't listed in the ebuild, literally at all.   The fact that these are already installed by other packages doesn't make this right.  I'll fix the entirely missing deps.

**Comment by blshkv** [comment] 2020-09-14 14:54
Please double check before fixing it. The deps are correct

**Comment by ZeroChaos-** [comment] 2020-09-14 15:00
The deps were NON-EXISTANT.  Fixed now, enjoy.

**Comment by blshkv** [comment] 2020-09-14 15:28
your "fix" doesn't make any sense at all. All these packages are getting pulled by dependencies in correct order.

**Closed** 2020-09-14 15:30 UTC

**Comment by blshkv** [comment] 2020-09-14 15:33
https://github.com/pentoo/pentoo-overlay/commit/c29ce7c50e22d5a3c6011af015a5dc1353c81129

**Comment by ZeroChaos-** [comment] 2020-09-14 15:33
do you even test things? It works fine on bundler 2 for me.  Your untested "fix" and untested revert are trying my patience.

**Comment by blshkv** [comment] 2020-09-14 15:36
something is trying to create that .lock file. It is clearly NOT missing dependencies

**Comment by ZeroChaos-** [comment] 2020-09-14 15:37
It works for me with bundler 2, so that's clearly not the issue either.  Maybe you should be testing instead of guessing?

**Comment by ZeroChaos-** [comment] 2020-09-14 15:41
and with no irony at all, the dep list I added to wpscan isn't matched in cmsscanner.  Awesome work

**Comment by blshkv** [comment] 2020-09-14 15:44
That list is populated from .gemspec -> s.add_dependency . Open upstream issue if anything is missing.

**Comment by xp-vit** [comment] 2020-09-14 15:48
I tried yesterday masking `dev-ruby/bundler:2`. It uses `dev-ruby/bundler-1.17.3-r1` and it fails with:

````
>>> Emerging (1 of 1) net-analyzer/wpscan-3.8.7::pentoo
 * wpscan-3.8.7.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                                                                     [ ok ]
>>> Unpacking source...
 * Running unpack phase for all ...
>>> Unpacking wpscan-3.8.7.tar.gz to /var/tmp/portage/net-analyzer/wpscan-3.8.7/work/all
>>> Source unpacked in /var/tmp/portage/net-analyzer/wpscan-3.8.7/work
>>> Preparing source in /var/tmp/portage/net-analyzer/wpscan-3.8.7/work ...
 * Running prepare phase for all ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby25 ...
 * Running prepare phase for ruby25 ...
Traceback (most recent call last):
/usr/bin/ruby25: No such file or directory -- bundle (LoadError)
 * ERROR: net-analyzer/wpscan-3.8.7::pentoo failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_prepare
 *   environment, line 2103:  Called ruby-ng_src_prepare
 *   environment, line 1762:  Called _ruby_each_implementation 'each_ruby_prepare'
 *   environment, line  535:  Called _ruby_invoke_environment 'ruby25' 'each_ruby_prepare'
 *   environment, line  656:  Called each_ruby_prepare
 *   environment, line  840:  Called die
 * The specific snippet of code:
 *       BUNDLE_GEMFILE=Gemfile ${RUBY} -S bundle install --local || die;
 * 
 * If you need support, post the output of `emerge --info '=net-analyzer/wpscan-3.8.7::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=net-analyzer/wpscan-3.8.7::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/net-analyzer/wpscan-3.8.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-analyzer/wpscan-3.8.7/temp/environment'.
 * Working directory: '/var/tmp/portage/net-analyzer/wpscan-3.8.7/work/ruby25/wpscan-3.8.7'
 * S: '/var/tmp/portage/net-analyzer/wpscan-3.8.7/work/ruby25/wpscan-3.8.7'

>>> Failed to emerge net-analyzer/wpscan-3.8.7, Log file:
````

**Comment by blshkv** [comment] 2020-09-14 15:50
I took random dep which you added (incorrectly):
dev-ruby/minitest pulled by activerecord which pulled by opt_parse_validator which pulled by cms_scanner which pulled by wpscan.

So no, the deps are correct. If bundler 2.0 works (I have no time to test) then some else is trying to create that .lock file.
Feel free to figure out which the latest and the greatest version of all these deps does that and report it.

Until then, there is nothing we can fix here

**Comment by blshkv** [comment] 2020-09-14 15:52
@xp-vit please inspect your ebuild.log and compare with our current (stable) packages:

```
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 1.7.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.4.3
Using public_suffix 4.0.6
Using addressable 2.7.0
Using bundler 1.17.3
Using ffi 1.11.3
Using get_process_mem 0.2.5
Using nokogiri 1.10.4
Using opt_parse_validator 1.9.2
Using ruby-progressbar 1.10.1
Using sys-proctable 1.2.6
Using ethon 0.12.0
Using typhoeus 1.4.0
Using xmlrpc 0.3.0
Using yajl-ruby 1.4.1
Using cms_scanner 0.12.1
Using wpscan 3.8.7 from source at `.`
```

**Comment by ZeroChaos-** [comment] 2020-09-14 17:24
differences available from earlier attached files
```
Using concurrent-ruby 1.1.7
Using i18n 1.8.5
Using minitest 5.14.2
Using tzinfo 1.2.7
Using zeitwerk 2.4.0
Using activesupport 6.0.3.3
Using bundler 2.1.4
Using ffi 1.13.1
Using nokogiri 1.10.10
Using sys-proctable 1.2.2
```
